# Generated by Django 5.2.6 on 2026-05-16 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_remove_order_orders_orde_user_id_37fed6_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="source_cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="orders.cart",
            ),
        ),
    ]
